# Generated by Django 3.1.7 on 2021-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', height_field=50, max_length=50, upload_to='Blogger/blog_img', width_field=50),
        ),
    ]
